tasks:
  - init: npm install
    command: npm run devel:debug
  - command: gp await-port 9000 && gp preview $(gp url 9000)/.netlify/functions/digit/200/5/12345
ports:
  - port: 9000
    onOpen: ignore
  - port: 9229
    onOpen: ignore
