[build]
publish = "public"
functions = "dist/api"
command = "npm run build"

[build.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[[redirects]]
    from = "/v1/*"
    to = "/.netlify/functions/:splat"
    status = 200
    force = true
