[build]
publish = "public"
functions = "dist/api"
command = "npm run build"

[build.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"

[[redirects]]
    from = "/v1/counter"
    to = "/.netlify/functions/counter"
    status = 200

[[redirects]]
    from = "/v1/digit/:width/:digit/:number/"
    to = "/.netlify/functions/digit/?width=:width&digit=:digit&number=:number&"
    status = 200
